name: 'Label maintenance'
on:
  schedule:
    - cron:  '0 18 * * *'

jobs:
  label_maintenance:
    name: Label maintenance
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Get @azu/github-label-setup
        run: yarn global add @azu/github-label-setup
      - run: pwd
      - run: ls -la
      - name: Run github-label-setup
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          `yarn global bin`/github-label-setup --token ${GITHUB_TOKEN}