name: 'Label maintenance'
on:
  push:
    paths:
      - '.github/labels.json'
  schedule:
    - cron: '0 4 * * *'

jobs:
  label_maintenance:
    name: Label maintenance
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Get @azu/github-label-setup
        run: yarn global add @azu/github-label-setup
      - run: cat /home/runner/work/repository-template/repository-template/.github/labels.json
      - name: Run github-label-setup
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          `yarn global bin`/github-label-setup --token ${GITHUB_TOKEN} --labels /home/runner/work/repository-template/repository-template/.github/labels.json
